{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.1.1-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bfe4xpgobzh7dnjrwlr36tbtfe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "elepay-2.1.1-beta01.aar",
          "url": "elepay-2.1.1-beta01.aar",
          "size": 2187087,
          "sha512": "374ccf2ff86fb97842a7f477ab3fdebccc18da62abfe255af2092c7976605629237eacf03d03579fff72a7f873021c418b277b781e7e55d2f48f8955d7f92903",
          "sha256": "344e163d73e7a237b544337220b814ef5d740672912e20eb927f5a581fa0e0dc",
          "sha1": "6470a0feaf335154759b64b1b48e530428e71a4d",
          "md5": "a73abca64257c1c8ac1370c8d7b3a241"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.1.1-beta01.aar",
          "url": "elepay-2.1.1-beta01.aar",
          "size": 2187087,
          "sha512": "374ccf2ff86fb97842a7f477ab3fdebccc18da62abfe255af2092c7976605629237eacf03d03579fff72a7f873021c418b277b781e7e55d2f48f8955d7f92903",
          "sha256": "344e163d73e7a237b544337220b814ef5d740672912e20eb927f5a581fa0e0dc",
          "sha1": "6470a0feaf335154759b64b1b48e530428e71a4d",
          "md5": "a73abca64257c1c8ac1370c8d7b3a241"
        }
      ]
    }
  ]
}
