{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "p4ixvpqeorgfhb3anmiuim6x6u"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "elepay-2.1.0-beta01.aar",
          "url": "elepay-2.1.0-beta01.aar",
          "size": 2194720,
          "sha512": "596112f4f3e4cda8be087b6b0b698e4c6a7dbb9f90478779c67a58cb5038d0c2d49eb390584011a92df9e9899249d699fe968623a95527204384f46e10dda7a9",
          "sha256": "bc10d20a8616f842f2919eecf0e4958ba3818a533749ef03e46a2a37c5f7f3f2",
          "sha1": "af3ae5046b03e89cebdbe7418924c21111c17f95",
          "md5": "94917fe34dda7bc5d4452f3279fcd979"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "14.4.1"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.1.0-beta01.aar",
          "url": "elepay-2.1.0-beta01.aar",
          "size": 2194720,
          "sha512": "596112f4f3e4cda8be087b6b0b698e4c6a7dbb9f90478779c67a58cb5038d0c2d49eb390584011a92df9e9899249d699fe968623a95527204384f46e10dda7a9",
          "sha256": "bc10d20a8616f842f2919eecf0e4958ba3818a533749ef03e46a2a37c5f7f3f2",
          "sha1": "af3ae5046b03e89cebdbe7418924c21111c17f95",
          "md5": "94917fe34dda7bc5d4452f3279fcd979"
        }
      ]
    }
  ]
}
