{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.6.0-beta01.aar",
          "url": "elepay-2.6.0-beta01.aar",
          "size": 2553298,
          "sha512": "2d56020896dba21a0e3d6fb7eb8ee08e15c4a60c17198435b5e2d496d80ab5f20a1e31cac50fbcce73875009f4a77b50bab068b34b200539381a1aa596982de6",
          "sha256": "5e6b1838056968cd8b8c44ddad839c4c422aab81c6cf184bdfbed2216637605f",
          "sha1": "211c01bf78f1459940c778e2b861a9eb7c3e8800",
          "md5": "0faacc468599048f207f07a54e9bbea4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.17.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "20.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.6.0-beta01.aar",
          "url": "elepay-2.6.0-beta01.aar",
          "size": 2553298,
          "sha512": "2d56020896dba21a0e3d6fb7eb8ee08e15c4a60c17198435b5e2d496d80ab5f20a1e31cac50fbcce73875009f4a77b50bab068b34b200539381a1aa596982de6",
          "sha256": "5e6b1838056968cd8b8c44ddad839c4c422aab81c6cf184bdfbed2216637605f",
          "sha1": "211c01bf78f1459940c778e2b861a9eb7c3e8800",
          "md5": "0faacc468599048f207f07a54e9bbea4"
        }
      ]
    }
  ]
}
