{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.2.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "gkkyqr2kqneptgirvnbrig74lu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "elepay-2.2.0-beta01.aar",
          "url": "elepay-2.2.0-beta01.aar",
          "size": 2224172,
          "sha512": "f556dda09ba7b70fc2cc2d5584d40b9fe034b7aaaa54f3b2e58a917bcf022e86811a9aa71545aed35a52c321ee1b087fa9742e585fd40460f25d75349c5730c4",
          "sha256": "221e7e973f0b627c1b8399fad3f052a60f8e93f1d815acd809c26ae269a976c7",
          "sha1": "d29eb934402749eb89951fae4e11bf02b4d5db77",
          "md5": "ce57541fce44c79f4bc4421abf2db89f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.2.0-beta01.aar",
          "url": "elepay-2.2.0-beta01.aar",
          "size": 2224172,
          "sha512": "f556dda09ba7b70fc2cc2d5584d40b9fe034b7aaaa54f3b2e58a917bcf022e86811a9aa71545aed35a52c321ee1b087fa9742e585fd40460f25d75349c5730c4",
          "sha256": "221e7e973f0b627c1b8399fad3f052a60f8e93f1d815acd809c26ae269a976c7",
          "sha1": "d29eb934402749eb89951fae4e11bf02b4d5db77",
          "md5": "ce57541fce44c79f4bc4421abf2db89f"
        }
      ]
    }
  ]
}
