{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.4.0-beta05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "lkug26c22nebhkimlv42oocioa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.4.0-beta05.aar",
          "url": "elepay-2.4.0-beta05.aar",
          "size": 2429742,
          "sha512": "be05712bd71c0831c2869a7d50d29511c0fddb59cdc2582409537cb1197accd1d53c51b823896651cd3041abd2f77b01694105ea8470d8dc9d4c66052c5a18b3",
          "sha256": "eacb2c7780f08e48156f31d45e8cd7da610e7d74f3dd1a474a097c9f6404ce9e",
          "sha1": "f918a9c2ceb0b77537274e2620fe94ca4364cb4d",
          "md5": "d2191c80947e054d559c6a3fa4044fd8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.4.0-beta05.aar",
          "url": "elepay-2.4.0-beta05.aar",
          "size": 2429742,
          "sha512": "be05712bd71c0831c2869a7d50d29511c0fddb59cdc2582409537cb1197accd1d53c51b823896651cd3041abd2f77b01694105ea8470d8dc9d4c66052c5a18b3",
          "sha256": "eacb2c7780f08e48156f31d45e8cd7da610e7d74f3dd1a474a097c9f6404ce9e",
          "sha1": "f918a9c2ceb0b77537274e2620fe94ca4364cb4d",
          "md5": "d2191c80947e054d559c6a3fa4044fd8"
        }
      ]
    }
  ]
}
