{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.6.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.6.0-beta02.aar",
          "url": "elepay-2.6.0-beta02.aar",
          "size": 2557412,
          "sha512": "85f3fbad40732da09d69b1a5bae781c39b3c57a5e2a313f108a104b5fc82a4644f53d5a2a2a2a8aa0791d53cdf8a8504ec2e5b69fe4fff54ae89e567ad78f298",
          "sha256": "56d4de6adf5afc19b87acc4ed3adc04ecb511f14723a3a095ec90e1aa0987bf4",
          "sha1": "0fc43fdc0f03d0a612319a42571310ba567457e3",
          "md5": "3ad186a18ef9ae1c6395b8cb65577bcd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.17.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "20.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.6.0-beta02.aar",
          "url": "elepay-2.6.0-beta02.aar",
          "size": 2557412,
          "sha512": "85f3fbad40732da09d69b1a5bae781c39b3c57a5e2a313f108a104b5fc82a4644f53d5a2a2a2a8aa0791d53cdf8a8504ec2e5b69fe4fff54ae89e567ad78f298",
          "sha256": "56d4de6adf5afc19b87acc4ed3adc04ecb511f14723a3a095ec90e1aa0987bf4",
          "sha1": "0fc43fdc0f03d0a612319a42571310ba567457e3",
          "md5": "3ad186a18ef9ae1c6395b8cb65577bcd"
        }
      ]
    }
  ]
}
