{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "3.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.3.0-beta01.aar",
          "url": "elepay-3.3.0-beta01.aar",
          "size": 1744893,
          "sha512": "c3e90c215722bff0852a078e82df3635053a96b8992b066b4efe7757ca42e103eb904ab272cdfffedcaf464bd9bef5975a535c82b6fc3296d544af0878a60624",
          "sha256": "7e1b5648a1e3d6cce568ca6d4e740558f9a74c3d6e9c668af639e6fc2f5044dc",
          "sha1": "f98a8b830273a3ad372fdb6c020f0e5f2d203a90",
          "md5": "51170e368a056d245b7161d710feff3b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripecardscan",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "text-recognition",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.3.0-beta01.aar",
          "url": "elepay-3.3.0-beta01.aar",
          "size": 1744893,
          "sha512": "c3e90c215722bff0852a078e82df3635053a96b8992b066b4efe7757ca42e103eb904ab272cdfffedcaf464bd9bef5975a535c82b6fc3296d544af0878a60624",
          "sha256": "7e1b5648a1e3d6cce568ca6d4e740558f9a74c3d6e9c668af639e6fc2f5044dc",
          "sha1": "f98a8b830273a3ad372fdb6c020f0e5f2d203a90",
          "md5": "51170e368a056d245b7161d710feff3b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "elepay-3.3.0-beta01-sources.jar",
          "url": "elepay-3.3.0-beta01-sources.jar",
          "size": 336045,
          "sha512": "41bc6f7827eda79ab92af02d37c44a91de694e38ad6120cf6f572d1d14d91cc654e99ab69f587a87c24d72c4c511f83e9d648dc321586f660a89e8b934dd07d1",
          "sha256": "44f7d5620160d3a52fa497ef25bb81abb7faa7da3e7fe3e5441714ca65118a4a",
          "sha1": "c1986f84b49defcf076e2bde8886f4df73a45c73",
          "md5": "a6d1402c6c4ac3304c4682c28937e5eb"
        }
      ]
    }
  ]
}
