{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "3.3.2-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.3.2-beta01.aar",
          "url": "elepay-3.3.2-beta01.aar",
          "size": 1745474,
          "sha512": "bd4c00f7d3caad0447996f4605f4bcef2f860a309fa5b4ed578fde0687f1d7742908a06cb175896235d7bd4a379fcf4216cf181a0070d0fdb0b9ebd134cd3349",
          "sha256": "5462c5689f51f430f5c3b0d0aaffa79e3acc91cfa25e80cafe56f7a7bec71c0e",
          "sha1": "b71f8954cc7bfb18bf800bb6e64b242e6fc346e8",
          "md5": "24680f69685b43ee36154ee2c81d25a6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripecardscan",
          "version": {
            "requires": "20.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "text-recognition",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-3.3.2-beta01.aar",
          "url": "elepay-3.3.2-beta01.aar",
          "size": 1745474,
          "sha512": "bd4c00f7d3caad0447996f4605f4bcef2f860a309fa5b4ed578fde0687f1d7742908a06cb175896235d7bd4a379fcf4216cf181a0070d0fdb0b9ebd134cd3349",
          "sha256": "5462c5689f51f430f5c3b0d0aaffa79e3acc91cfa25e80cafe56f7a7bec71c0e",
          "sha1": "b71f8954cc7bfb18bf800bb6e64b242e6fc346e8",
          "md5": "24680f69685b43ee36154ee2c81d25a6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "elepay-3.3.2-beta01-sources.jar",
          "url": "elepay-3.3.2-beta01-sources.jar",
          "size": 336635,
          "sha512": "09d0a9db310ea0df2f9f480f1ee7ce1c599683c03574fd1d9152801f81d628b1dc34eeac2a2d5ef41e920a3545bc18bbfdf0661f12314d9b2d396ee72072d08b",
          "sha256": "6e2b8a810cadc8695c2b7e0c831dc01bd12936c2b4254d16497aad8712af07e1",
          "sha1": "999cbf9400fc89ce06ffca7842fb7b00b1ea3561",
          "md5": "599069c133a0f108264d54c8caaa7692"
        }
      ]
    }
  ]
}
