{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.2.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "3lxsi4rtojgr5oq3fzw2xitvqy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "elepay-2.2.0-beta02.aar",
          "url": "elepay-2.2.0-beta02.aar",
          "size": 2222381,
          "sha512": "bc0c04827fe2e344cd85679e869f2b035b537942b7b2e79f2545a8c8fe0cf98cb5dc6614347238a1fa41c47415bf2a35d01ec437bab95fed5e69a3c4ff49ece4",
          "sha256": "b776e1d454feaaad9922beb20c84f0813982447de24c394c59cdaf0878f395ee",
          "sha1": "6257765fd834ba9bb75f8f681a2eff7d71a63e92",
          "md5": "a132a6f1239152359bb4cc1b09399684"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.2.0-beta02.aar",
          "url": "elepay-2.2.0-beta02.aar",
          "size": 2222381,
          "sha512": "bc0c04827fe2e344cd85679e869f2b035b537942b7b2e79f2545a8c8fe0cf98cb5dc6614347238a1fa41c47415bf2a35d01ec437bab95fed5e69a3c4ff49ece4",
          "sha256": "b776e1d454feaaad9922beb20c84f0813982447de24c394c59cdaf0878f395ee",
          "sha1": "6257765fd834ba9bb75f8f681a2eff7d71a63e92",
          "md5": "a132a6f1239152359bb4cc1b09399684"
        }
      ]
    }
  ]
}
