{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "bqncesprrbfyjovrecfgd7rg3a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "elepay-2.3.0-beta01.aar",
          "url": "elepay-2.3.0-beta01.aar",
          "size": 2227408,
          "sha512": "815a4f6c6fbe756b98e1d77f1dafd569f01c695990b51c9bafb298b7b15608185e24696deaa92414c0702de0e36b1369192c22b0e878b4f74436176cf4096777",
          "sha256": "336f9b5c320be6961c0b3fc9a3b947ded9bb37e75dcedbced61d03f8e1c791cb",
          "sha1": "2a874e297eafef46c5a6dab832451671a7a7316a",
          "md5": "449378067f967503be7670931b57159b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.3.0-beta01.aar",
          "url": "elepay-2.3.0-beta01.aar",
          "size": 2227408,
          "sha512": "815a4f6c6fbe756b98e1d77f1dafd569f01c695990b51c9bafb298b7b15608185e24696deaa92414c0702de0e36b1369192c22b0e878b4f74436176cf4096777",
          "sha256": "336f9b5c320be6961c0b3fc9a3b947ded9bb37e75dcedbced61d03f8e1c791cb",
          "sha1": "2a874e297eafef46c5a6dab832451671a7a7316a",
          "md5": "449378067f967503be7670931b57159b"
        }
      ]
    }
  ]
}
