{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.9.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.9.0-beta01.aar",
          "url": "elepay-2.9.0-beta01.aar",
          "size": 1840054,
          "sha512": "4b2df93712e5653f0d21e20fe21f06a279c287e65fcf2e047e7d59e6d996099a1b9591c7c3f557244e54090c1fdda8a6655575fd2908538a2d372cbfe901687b",
          "sha256": "77afc2cd250ff486d50935f2d4e01e96c80dc2308e50230cdb38f7299025c086",
          "sha1": "967700506006aa4343a801a3c2371ea842504d37",
          "md5": "44b73fdc37f5645bc5edd6f4b30c881b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.17.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.9.0-beta01.aar",
          "url": "elepay-2.9.0-beta01.aar",
          "size": 1840054,
          "sha512": "4b2df93712e5653f0d21e20fe21f06a279c287e65fcf2e047e7d59e6d996099a1b9591c7c3f557244e54090c1fdda8a6655575fd2908538a2d372cbfe901687b",
          "sha256": "77afc2cd250ff486d50935f2d4e01e96c80dc2308e50230cdb38f7299025c086",
          "sha1": "967700506006aa4343a801a3c2371ea842504d37",
          "md5": "44b73fdc37f5645bc5edd6f4b30c881b"
        }
      ]
    }
  ]
}
