{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.4.1-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.4.1-beta02.aar",
          "url": "elepay-2.4.1-beta02.aar",
          "size": 2433053,
          "sha512": "f58e7df94d1567ce774b50790b6efac1774dea4d798289904c181af8f82a16ae22f9f19b0f4521dcb4e7bb31bd03ce2ac0dac9a76dd546ff81e99f2b51a22df6",
          "sha256": "fc3a3bba126e00de0a8c2a1d4b157fc40aa4f29fbdebe5d566722784f21cd9d4",
          "sha1": "a9b91f3151e6d5a7790318b0c5b4cf33239a66a4",
          "md5": "efe7fc6855c67bdbee7a1adbe032a6e5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.10.0"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.17.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.4.1-beta02.aar",
          "url": "elepay-2.4.1-beta02.aar",
          "size": 2433053,
          "sha512": "f58e7df94d1567ce774b50790b6efac1774dea4d798289904c181af8f82a16ae22f9f19b0f4521dcb4e7bb31bd03ce2ac0dac9a76dd546ff81e99f2b51a22df6",
          "sha256": "fc3a3bba126e00de0a8c2a1d4b157fc40aa4f29fbdebe5d566722784f21cd9d4",
          "sha1": "a9b91f3151e6d5a7790318b0c5b4cf33239a66a4",
          "md5": "efe7fc6855c67bdbee7a1adbe032a6e5"
        }
      ]
    }
  ]
}
