{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.elestyle.androidapp",
    "module": "elepay",
    "version": "2.4.1-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.4.1-beta01.aar",
          "url": "elepay-2.4.1-beta01.aar",
          "size": 2433243,
          "sha512": "dfdfbf75ba7948a168900b079c0c5c25e61ac118c321ef286793d8e5c55874e463ad0fca80ada6c592ee278fdd216837076c2ed02558f5a08bb93af6696fa6c6",
          "sha256": "cd0350b427bec6c4dcf67197c85aeaeccbaba6b847fdce225e8c11f7805b821c",
          "sha1": "2ea973b1d4181380bd8a907ecd11b4671b35c65f",
          "md5": "dafb2eb1b7fb135d9b9b51acdef2a8b9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "16.10.0"
          }
        },
        {
          "group": "com.braintreepayments.api",
          "module": "braintree",
          "version": {
            "requires": "3.17.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "18.1.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-safetynet",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "elepay-2.4.1-beta01.aar",
          "url": "elepay-2.4.1-beta01.aar",
          "size": 2433243,
          "sha512": "dfdfbf75ba7948a168900b079c0c5c25e61ac118c321ef286793d8e5c55874e463ad0fca80ada6c592ee278fdd216837076c2ed02558f5a08bb93af6696fa6c6",
          "sha256": "cd0350b427bec6c4dcf67197c85aeaeccbaba6b847fdce225e8c11f7805b821c",
          "sha1": "2ea973b1d4181380bd8a907ecd11b4671b35c65f",
          "md5": "dafb2eb1b7fb135d9b9b51acdef2a8b9"
        }
      ]
    }
  ]
}
